version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: shareit-db
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  shareit-server:
    build:
      context: ./server  # путь к папке с Dockerfile shareit-server
    container_name: shareit-server
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "9090:9090"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://shareit-db:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 1234
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    restart: on-failure

  shareit-gateway:
    build:
      context: ./gateway  # путь к Dockerfile shareit-gateway
    container_name: shareit-gateway
    depends_on:
      - shareit-server
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
    restart: on-failure
