spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234

---

spring:
  config:
    activate:
      on-profile: ci
  datasource:
    url: jdbc:postgresql://postgres:5432/postgres
    username: postgres
    password: 1234